dataset_variables_types:
  application_test:
    categorical_nominal: &id001
    - FONDKAPREMONT_MODE
    - FLAG_EMAIL
    - WEEKDAY_APPR_PROCESS_START
    - CODE_GENDER
    - NAME_TYPE_SUITE
    - FLAG_MOBIL
    - NAME_EDUCATION_TYPE
    - FLAG_PHONE
    - EMERGENCYSTATE_MODE
    - FLAG_OWN_REALTY
    - NAME_CONTRACT_TYPE
    - FLAG_CONT_MOBILE
    - WALLSMATERIAL_MODE
    - NAME_FAMILY_STATUS
    - NAME_HOUSING_TYPE
    - HOUSETYPE_MODE
    - FLAG_WORK_PHONE
    - NAME_INCOME_TYPE
    - FLAG_EMP_PHONE
    - FLAG_OWN_CAR
    categorical_ordinal: &id002
    - REGION_RATING_CLIENT
    - REGION_RATING_CLIENT_W_CITY
    datetime: &id003
    - HOUR_APPR_PROCESS_START
    numerical_continuous: &id004
    - COMMONAREA_AVG
    - BASEMENTAREA_MODE
    - NONLIVINGAPARTMENTS_MODE
    - EXT_SOURCE_3
    - ELEVATORS_AVG
    - YEARS_BEGINEXPLUATATION_MODE
    - COMMONAREA_MODE
    - FLOORSMAX_MEDI
    - BASEMENTAREA_AVG
    - AMT_INCOME_TOTAL
    - LANDAREA_AVG
    - EXT_SOURCE_1
    - REGION_POPULATION_RELATIVE
    - BASEMENTAREA_MEDI
    - APARTMENTS_MODE
    - NONLIVINGAREA_MODE
    - YEARS_BUILD_AVG
    - NONLIVINGAPARTMENTS_AVG
    - NONLIVINGAREA_AVG
    - NONLIVINGAPARTMENTS_MEDI
    - LIVINGAPARTMENTS_MODE
    - FLOORSMIN_AVG
    - EXT_SOURCE_2
    - FLOORSMAX_AVG
    - AMT_CREDIT
    - LIVINGAREA_MEDI
    - LIVINGAPARTMENTS_AVG
    - ENTRANCES_AVG
    - LANDAREA_MODE
    - ELEVATORS_MEDI
    - YEARS_BUILD_MODE
    - ENTRANCES_MEDI
    - YEARS_BEGINEXPLUATATION_MEDI
    - COMMONAREA_MEDI
    - AMT_ANNUITY
    - FLOORSMIN_MODE
    - FLOORSMIN_MEDI
    - ELEVATORS_MODE
    - YEARS_BEGINEXPLUATATION_AVG
    - FLOORSMAX_MODE
    - APARTMENTS_AVG
    - LANDAREA_MEDI
    - LIVINGAREA_MODE
    - LIVINGAREA_AVG
    - YEARS_BUILD_MEDI
    - ENTRANCES_MODE
    - TOTALAREA_MODE
    - APARTMENTS_MEDI
    - LIVINGAPARTMENTS_MEDI
    - AMT_GOODS_PRICE
    - NONLIVINGAREA_MEDI
    numerical_discrete: &id005
    - AMT_REQ_CREDIT_BUREAU_HOUR
    - AMT_REQ_CREDIT_BUREAU_DAY
    - AMT_REQ_CREDIT_BUREAU_WEEK
    - AMT_REQ_CREDIT_BUREAU_MON
    - AMT_REQ_CREDIT_BUREAU_QRT
    - AMT_REQ_CREDIT_BUREAU_YEAR
    - DAYS_BIRTH
    - DAYS_ID_PUBLISH
    - DAYS_EMPLOYED
    - DAYS_LAST_PHONE_CHANGE
    - DAYS_REGISTRATION
  application_train:
    categorical_nominal: *id001
    categorical_ordinal: *id002
    datetime: *id003
    numerical_continuous: *id004
    numerical_discrete: *id005
target:
- TARGET
